# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 858db1722f2e0ac5085e3071b97c7a3f9407f7580bb28dbf98a378bcbc4895903ee40b0e84389717d09579cec25b935494bc20bd44251c11cddaeb7c4dad923e

test:
  secret_key_base: 003f79d68ef314ddc67a75f5c1219882238b9edee4d07dc4eb0ba89b5f4084e42e59390edadaf453d023e23f7c3147e3e356bba9fce3d8cc42a2f7c63f888657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
